// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2oUFreQm1tsP5DfqwgGIdY4fiBEhUeT8',
    appId: '1:430266489542:web:9a3faf5eff83c4680dd5c7',
    messagingSenderId: '430266489542',
    projectId: 'appmantenimiento-8ad77',
    authDomain: 'appmantenimiento-8ad77.firebaseapp.com',
    storageBucket: 'appmantenimiento-8ad77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgvn-roEd_oigsSPs55gwBfpIm0R9Z1A8',
    appId: '1:430266489542:android:219cdf1dab18e0bc0dd5c7',
    messagingSenderId: '430266489542',
    projectId: 'appmantenimiento-8ad77',
    storageBucket: 'appmantenimiento-8ad77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPFSLDNWLH-lyD5aWq9Q11vvBpdHVrKc',
    appId: '1:430266489542:ios:20b49cf851e2e4d30dd5c7',
    messagingSenderId: '430266489542',
    projectId: 'appmantenimiento-8ad77',
    storageBucket: 'appmantenimiento-8ad77.appspot.com',
    iosBundleId: 'com.example.proyectoAppMantenimiento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPFSLDNWLH-lyD5aWq9Q11vvBpdHVrKc',
    appId: '1:430266489542:ios:20b49cf851e2e4d30dd5c7',
    messagingSenderId: '430266489542',
    projectId: 'appmantenimiento-8ad77',
    storageBucket: 'appmantenimiento-8ad77.appspot.com',
    iosBundleId: 'com.example.proyectoAppMantenimiento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2oUFreQm1tsP5DfqwgGIdY4fiBEhUeT8',
    appId: '1:430266489542:web:4dbcaa66f83c23b30dd5c7',
    messagingSenderId: '430266489542',
    projectId: 'appmantenimiento-8ad77',
    authDomain: 'appmantenimiento-8ad77.firebaseapp.com',
    storageBucket: 'appmantenimiento-8ad77.appspot.com',
  );
}
